### ISSUE TITLE
Can't close down application. 

### ISSUE THREAD

**Issue by Ryanb58** [antelle/keeweb#108]
Sisuation:
Fedora 22 w/ i3

Can't close out of the application because it does not support the CTRL + Q shortcut nor ALT+F4. i3 does not have any system borders around an application.

**Comment by antelle** [comment]
I need some help about this as I'm not familiar with Fedora

**Comment by Ryanb58** [comment]
Basically, it would be nice to have a keyboard shortcut that will close out of the application when needed. I vote for CTRL + Q(for Linux users) and ALT + F4(for Windows users). I'll check into adding a pull request for this in the near future.

**Comment by antelle** [comment]
But isn't there any system shortcut which would trigger window close event? For now, we are binding to system close event rather than specific shortcuts. I was sure it would work everywhere, and I'm very surprised it does not. Pull request would be awesome, as setting up Fedora will take some time. But if you are not familiar with code, it's okay, I'll set Fedora and fix it, this will happen a bit later though.

**Comment by Ryanb58** [comment]
There is: 
https://i3wm.org/docs/userguide.html#_closing_windows

However, I don't believe you want us to force quitting the application. I was scanning the other issues and heard talk about a popup that is displayed when exiting out of the application? This does not occur when I use the system close shortcut(if such a thing exists).

**Comment by antelle** [comment]
Hm, the link you provided describes force-close (like 'ctrl-alt-del + kill task' on windows, or 'force quit' on mac), but is there anything like normal close key (on Windows it's Ctrl+F4, on Mac Cmd-Q)?

**Comment by thomas-holmes** [comment]
After a bit of experimenting (XMonad & Arch Linux) I found I am cleanly exiting when using my window manager provided window closing functionality.

I had to disable "Automatically save and sync" in general settings to actually trigger the prompt since normally it was already saved before I got around to quitting.

If you disable that setting, add an entry, and then quit do you see the dialog @Ryanb58?

**Comment by Ryanb58** [comment]
@thomas-holmes you are a great person! That reproduced the pop-up when I did my CTRL+SHIFT+Q command. Appears that the i3 window manager does allow for program interruption upon quitting an application. I would say this issue is solved. 

:) Thanks!

**Comment by AlexWayfer** [comment]
I can't close app with `Ctrl+Q` or `Ctrl+Shift+Q` :(

With enabled `Automatically save and sync` setting or disabled.

Can somebody help?

Arch Linux, Gnome 3.
