### ISSUE TITLE
[Feature request] Ubuntu touch ( ubuntu phone ) 

### ISSUE THREAD

**Issue by davidwed** [antelle/keeweb#121]
It would be nice if you can provide the Keeweb as a web-app ( scope ) at the ubuntu store.

**Comment by antelle** [comment]
Platform-specific apps (Universal Windows App, Ubuntu WebApp) will not be supported as it requires too much platform-specific code. Later mobile apps may be created with Cordova, or PhoneGap, maybe something else... But it's under consideration for now, because speed has to be investigated. Closing as not applicable for now.

**Comment by antelle** [comment]
related: #6
