### ISSUE TITLE
[Question] Is the web version secure?

### ISSUE THREAD

**Issue by qgustavor** [antelle/keeweb#122]
I checked some opened and closed issues and seems this question wasn't asked before. It seems related with #111 but the solutions showed there are not sufficient:

The *old* problem with web applications with handle crypto is that browsers check signatures only from the server, not from the code ([more info](https://tonyarcieri.com/whats-wrong-with-webcrypto#https-doesn39t-solve-this-problem)). Trying to implement some JavaScript based verification, like MEGA did, don't solve the problem as can be tampered if the servers which host it get attacked.

I imagined some solutions for this problem like applying a sign verification script, allowing users to read the source code of this verification script, audit it and/or verify this authenticity, *also* disabling auto-updates on this script (implemented [here](https://wshp.tk), but discontinued) or on the whole application (implemented [here](https://safeme.ga)). Those examples were too simplistic and because that I think those don't apply well to real applications like this one.

I don't want you to create other Cryptocat, which started as a web application then turned into a browser extension (IIRC) following the solutions from the linked article. I think is good to have a web version, even with those risks. Maybe a warning like [the one from TweetNaCl](https://tweetnacl.js.org/) could alert users about the limitations of the web version (it is subject to attacks) and the application itself (if it was reviewed or not).

**Comment by antelle** [comment]
So, you are speaking about the risk of servers (particularly github pages) being attacked?
First, this risk is very low (however the possibility is not zero).
As a solution, you offer sort of code signing for web. Well, this made be done in 2 ways:
1. Some user-script which will check the app hash after updating - but I think it must be a side-script, not mine. Do you know any existing solutions?
2. Check on appCache update: now the app is just downloading new version and installs it to cache, until manifest is updated; in theory, we can check if the new version is okay and only after it use it, otherwise continue with old one. This has an advantage that the user don't have to install anything, but of course this will work only on updates, not for new users;
3. Pinging of with periodic checks that the content is original - in cobmination with 2. it will give also more secure versions for new users.

**Comment by antelle** [comment]
Closing as the question seems to be answered. I've put down the idea of webapp self-checking to [Random Ideas](https://github.com/antelle/keeweb/wiki/Random-Ideas) page.
