### ISSUE TITLE
[Question] Paranoid version

### ISSUE THREAD

**Issue by samic130** [antelle/keeweb#126]
Is there anyway of having a paranoid web version?
Something that doesn't even check for updates, doesn't support any cloud storage, ...
No internet at all. A very off-line version.

**Comment by antelle** [comment]
Yes, it's called desktop and can be downloaded here: https://github.com/antelle/keeweb/releases/latest
> doesn't even check for updates

but you should disable it in settings, by default it checks and shows update bubble
> doesn't support any cloud storage

what? doesn't SUPPORT? It supports but will never connect without your command. simply don't click Dropbox button if you don't want it.
> No internet at all. 

Absolutely. The internet is not required for it.

**Comment by samic130** [comment]
OKAY!!
Calm down!
I can't use the desktop version because I want to use it on Chromebook.
In any case it was just an suggestion based on a need.

**Comment by antelle** [comment]
Then you can save HTML file and just open it to launch (or it's not possible on chromebook as well?). Or upload to your server and update only when required.

**Comment by samic130** [comment]
Yeah that was what I asked for in the first place. (A web-only version that
doesn't connect to the Internet)
I don't understand why you are acting like this! I'm just expressing my
need!

**Comment by antelle** [comment]
> I don't understand why you are acting like this!

I'm sorry if the answer seems impolite to you, I didn't mean that.
To me, uploading to your own server, or opening offline file, or the fact that web version will check for updates is obvious. Also, as it's maybe not written clearly, there are _very many_ users writing me that desktop version would be better, that's why the first thing I done is mention that completely offline desktop version do exists. If you know about desktop but cannot use it, it's another case but I cannot guess. I thought, you were one of them, who didn't see 'we have desktop builds' warnings nearly on each page.

**Comment by samic130** [comment]
Good that there isn't any confusion any more.
Back to business!
Is there any way to make an off-line version of the web version?
I'm more thinking about this:
https://play.google.com/store/apps/details?id=keepass2android.keepass2android_nonet
in comparison to:
https://play.google.com/store/apps/details?id=keepass2android.keepass2android&hl=en
Thanks

**Comment by antelle** [comment]
:+1: 
1. cloud storages
I've had a brief look on both of these apps: so the main difference between them is that offline version saves file locally and online version saves the file in cloud.
In contrast to that, we always let the user decide, whether to upload your file to the cloud or not, so this app is a combination of that two those apps: if you want, you activate dropbox and save to it; if not, you just open a local file. The Dropbox module is even not activated before you click Dropbox button. And if you click it, you will see Dropbox login and link approval; so unless you linked the app to Dropbox, the module code is here but it can do (and it will not try to do) nothing without your permission.
So I think you should be ok with this.

2. updater
Auto-updating of the web app is currently not optional and, to be honest, I don't see a way to disable it for the web app. Ways you may find useful for you:
- upload the certain version to your server and use from it
- use tagged builds from gh-pages branch, for example: I want version 1.0.0, I can find it here: https://github.com/antelle/keeweb/commits/gh-pages (but it's not possible to just open the web app from it, as github gives you the file as text content, not html), so re-upload is necessary here
- save the web page and use it: I don't know whether saving is possible in cloud OSes, like ChromeOs, so it might not fit you well

**Comment by samic130** [comment]
Thank you very much.

**Comment by nopivnick** [comment]
@antelle 

> save the web page and use it: I don't know whether saving is possible in cloud OSes, like ChromeOs, so it might not fit you well

I've been playing with a new Chromebook and saving https://app.keeweb.info/ locally as keeweb.html.

it seems to be working but (unless I'm mistaken) this arrangement puts the onus is on me to keep track of new releases, correct?

would it be very involved to have the javascript saved in keeweb.html check for a newer version of the web app whenever the machine is online and the browser loads keeweb.html? that way at least I would know when to download and overwrite the keeweb.html file with the latest version.

n.

**Comment by antelle** [comment]
@nopivnick yes, you're right. But you can automate this, i.e. create some sort of download script to check the manifest and download html, if it's not the same.
Checking updates is a bit difficult thing because of privacy issues: if I have downloaded the html, probably I don't expect it to send requests. So, I don't know if it would be useful for anyone outside ChromeOs.
// I suggest that you don't read comments in this issue, because I see that op has removed some comments (the most "interesting" parts of them) including the first one, so my answers here could be irrelevant.

**Comment by nopivnick** [comment]
@antelle 

> (the most "interesting" parts of them)

yeah, I figured as much.

n.
