### ISSUE TITLE
KeePassX cannot open, alert History element in history entry

### ISSUE THREAD

**Issue by jk2K** [antelle/keeweb#23]
open the saved kdbx file with using keeweb, KeePassX alert
```
Unable to open the database.
History element in history entry
```

KeeWeb v0.1.1 (built at 2015-11-04)
Environment: electron v0.34.0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/0.1.1 Chrome/45.0.2454.85 Electron/0.34.0 Safari/537.36

**Comment by antelle** [comment]
Thanks. I guess, you changed something in entry and then this happened after save? I'll check this.
If you have a test db with this, that would be great.

**Comment by antelle** [comment]
Yes, empty `<History/>` element is inserted to history entries, which is incorrect. KeePass is ok with that but other clients may treat as error. I'll fix it.

**Comment by jk2K** [comment]
Thanks for you work, 🙏

**Comment by antelle** [comment]
The fix will be available soon. 
But how do you open kdbx files with KeePassX? According to [FAQ](https://www.keepassx.org/faq), they don't support kdbx.

**Comment by antelle** [comment]
I figured it out. Beta 2 can open kdbx, and after this fix files can be opened without errors, thank you.

**Comment by jk2K** [comment]
Still have a small problem, Now it alerts
```
Unable to open the database.
Invalid uuid value
```

**Comment by antelle** [comment]
That's really weird, thanks for help for making it more clear.
I've tested different cases and got a lot of keepassx errors.
Then I looked into [keepassx reader source](https://github.com/keepassx/keepassx/blob/master/src/format/KeePass2XmlReader.cpp#L565), and there are many inconsistencies between keepassx and keepass read style (keepassx is more strict). For example, `EnableSearching` value: keepassx understands `false`, `true`, `null` - otherwise, throws error, while keepass understands, `false`, `true` and treats anything else as null.
Unfoutunately, keepass doesn't have any XSD for its internal XML, so it's not an easy task, to make it work. I'll look into keepassx source and make it fully compatible soon but I need some time for that, I hope to finish in a couple of days.

**Comment by jk2K** [comment]
very thankful

**Comment by antelle** [comment]
So far, I've fixed all the issues I've found. Now the format should be compatible. The app has been updated. Please note: this applies to new files created with KeeWeb. Files created before this fix will not be compatible.

**Comment by jk2K** [comment]
Now KeePassX alerts
```
Unable to open the database.
Invalid number value
```
btw, how to download the latest DMG file?

**Comment by antelle** [comment]
Please, check app version in Settings/Help. Is it 0.2.1? It seems to me, that error was in previous version. The app just loads web page so there's no need to download dmg. For now, update is a mess, so you may need to restart the app to make sure you have the latest version. I'm working on it, soon auto-update will be ok.

**Comment by jk2K** [comment]
Thanks, KeePassX can open the file created with KeeWeb now. But for the file before, what should i do?

**Comment by antelle** [comment]
That's perfect. To open files created before, you can open them with KeePass and just save.
Is this critical for you? If yes, I can create a fix, so that such issues in files will be auto-fixed on open, so they will be ok after save.

**Comment by jk2K** [comment]
doesn't matter, just let it be
Many thanks for your patience😄
