### ISSUE TITLE
Confusing versioning

### ISSUE THREAD

**Issue by kavolorn** [antelle/keeweb#28]
I've just installed app using link for .dmg from this page:

<img width="969" alt="screenshot 2015-11-11 21 37 35" src="https://cloud.githubusercontent.com/assets/2448274/11100992/175ae3f0-88bd-11e5-8d9d-55c8309280d2.png">

I expect it to be 0.2.0 version. When I check version in the app itself I see this version:

<img width="396" alt="screenshot 2015-11-11 21 41 27" src="https://cloud.githubusercontent.com/assets/2448274/11101007/2f7bccc4-88bd-11e5-9c1a-73a9d90bd785.png">

Taking into account message for 87a26a commit I expect to see column sizes preserved between app relaunches. But it seems not working.. On each launch they are default one. Maybe it's expected..

**Comment by antelle** [comment]
You're right, versioning totally sucks for now. I've even put it down to the README. Updates are now awful, sorry about that.

There are several disturbing issues:
- webapp should be refreshed twice after release
- desktop app (which consists of two parts: launcher script and webpage) can update only webpage
- updates cannot be turned off on desktop
- desktop app actually doesn't have any content and first install cannot be completed without Internet as it just loads the app page into launcher
- the user has no notification on updates

Taken into account all of these issues, I'm working on updater module which will allow to install updates smoothly or allow to turn them off. This is not so easy because [electron](http://electron.atom.io/) (desktop app wrapper which launches this app) doesn't provide built-in auto-update feature.

I expect the updater to be complete by this weekend.

Regarding column sizes: I've implemented saving but this will be in the next version, I haven't built the release with it yet.

**Comment by antelle** [comment]
Auto-update has landed so far. All issues I've mentioned have been resolved.
Please note: updates are downloaded as patches, so About box will always show the app version you have downloaded, and I don't know how to resolve this, because version shown in About box is stored in Info.plist file which is inaccessible to change by security settings. So to change it, we should re-download the app (which of course is not an option). I'll be think how to fix this in future but I consider it to be a minor issue. Correct running version is in Settings/Help section.

**Comment by kavolorn** [comment]
Thats nice! Thanks :+1: 

About automatic updates.. Is it possible to disable them? When we are talking about security I don't want something critical to be updated at the background. It is the right place to inject malicious code.

**Comment by antelle** [comment]
Of course, there's a checkbox to disable.
Hm, having notifications with disabled updates makes sense. I'll replace this checkbox with select having 3 options: 
- auto check and install (will be default option)
- don't check for updates at all
- check but don't install

**Comment by kavolorn** [comment]
Sorry, I see a check box!

**Comment by kavolorn** [comment]
Yes, that make sense to see changes without automatic updates. A bit more secure in my opinion :)

P. S. I see also width is being saved properly now :+1:

**Comment by antelle** [comment]
Thanks, I've added this feature to new [release schedule](https://github.com/antelle/keeweb/blob/master/TODO.md#todo).
