### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by skive** [antelle/keeweb#32]
When moving a mouse over an application window, some unwanted visual effects on text appears. It looks like an antialiasing is fastly switching on/off.

OS: Windows 10 Pro.

**Comment by antelle** [comment]
Please, copy browser or app info from Settings/Help.

**Comment by antelle** [comment]
> OS: Windows 10 Pro.
Ok, I assume you're using the app. I have windows 10 only on virtual pc, and it behaves ok. That's weird... What kind of effects are there? Please, make a screenshot of it.

**Comment by skive** [comment]
I'm using app. 
KeeWeb v0.3.0 (f7fa11a, 2015-11-14)
Environment: electron v0.34.0
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) KeeWeb/0.2.0 Chrome/45.0.2454.85 Electron/0.34.0 Safari/537.36

I will try to make a gif.

**Comment by skive** [comment]
http://www.upload.ee/image/5337474/1.gif

**Comment by antelle** [comment]
That's really strange, looks like Electron/Blink issue. I'll try to investigate, thaks.

**Comment by antelle** [comment]
Some users also report blurred appearance on windows with retina.
May be related: https://github.com/atom/electron/issues/3349

**Comment by antelle** [comment]
The issue have been investigated and fixed in v0.4.6. Please, test it and reopen, if it repeats.
I've tested in on Windows 10 and Ubuntu, for now there are no app repaints and should be no glitches.
If auto-update doesn't work for you: [here's a Windows build](https://github.com/antelle/keeweb/releases/download/v0.4.6/KeeWeb.win32.exe).

Haven't noticed any blurry themes on HD displays: I haven't run into this issue under Windows 10 on MBP retina and I haven't got another HD display, so closing it.
