### ISSUE TITLE
Buttons for copy login or password to clipboard [feature request]

### ISSUE THREAD

**Issue by Rurik19** [antelle/keeweb#34]
It shoud be very useful to have buttons for copy login or password to clipboard in list and\or in card.
Without this the app is quite unuseful on mobile devices.

**Comment by antelle** [comment]
To copy login, or password, or any field, click its title. No buttons will be added.
It's not so clear for now, that's why I've planned help/tips task, so the user will see a tip "You can click me to copy" the first time he opens the app.
On mobile devices, it can be buggy for now (I've tested only iOS Safari), as mobile devices have very basic support, mobile bugfixes are planned for Jan'16.

**Comment by antelle** [comment]
To copy password from list, select entry ant hit Cmd/Ctrl-C.

**Comment by Rurik19** [comment]
ok. if you want to test something on Windows 10 Mobile with Edge browser - just say me!

**Comment by antelle** [comment]
Yes, thanks, I'm planning to test on iOS, Android and Windows Mobile. Currently I have no Win devices. I'm going to test this in emulator first and hope it will work but real device of course can have some issues...
