### ISSUE TITLE
Show a passive notification when the password is copied

### ISSUE THREAD

**Issue by ismail** [antelle/keeweb#50]
When you do CTRL-C the application copies password to the clipboard but shows no notification. A passive popup with something like "Password copied to clipboard" would be very useful.

Also it should show a progress-bar for time-out to clearing clipboard if its enabled in settings.

**Comment by antelle** [comment]
:+1: Notification will be added in help/tips task. Also a tip that field titles are clickable.
I disagree with progress-bar, there's no need in it. Flow for 90+% cases: copy password, go to another app, paste, work with it. If was not pasted, return and copy again. Cleared clipboard will not be a surprise because default setting is 'Never clear'.

**Comment by ismail** [comment]
Well there is a case for the cleared clipboard because, I might try to paste it twice or more, and will be confused when it doesn't work :)
