### ISSUE TITLE
[Feature Request] Universal Windows App

### ISSUE THREAD

**Issue by p11sam1** [antelle/keeweb#6]
I love the work you are doing! It would be nice to have the app as an UWP so that I were able to run it on my Windows Phone.

**Comment by Sigmanor** [comment]
+1

**Comment by antelle** [comment]
Mobile apps are planned but for now, I'll focus on bugfixes, stability and issues listed in TODO; later I'm going to use maybe phonegap, cordova or some wrapper like that, I don't know for now.

**Comment by antelle** [comment]
Closing this as out of scope.
Mobile apps, if considered to be developed, will use platform-neutral technology, like Cordova, React Native, NativeScript and like that.

**Comment by fernandoluizao** [comment]
Are you still considering this? I'm inclined to develop a wrapper using cordova, will you accept this kind of contribution or is better to create another project on github?

**Comment by antelle** [comment]
Currently it's not at the top of my agenda, according to the [roadmap](https://github.com/keeweb/keeweb/wiki/TODO).
Creating a wrapper will also require a lot of support in the app code itself, for example:
- making ui controls usable on mobile devices
- dropbox/grdive/... auth
- open files from device
- ...
That's why it's not created yet: currently there are no resources to handle all this stuff and develop new features for both web and mobile.
So, if you would like to develop and support it, you can do it of course.

**Comment by fernandoluizao** [comment]
I will give a shoot.

Thanks!

**Comment by fernandoluizao** [comment]
Unfortunately not. I started to do, but there were other priorities at work
and I ended up abandoning.

Em seg, 21 de jan de 2019 13:28, Jared Pickerell <notifications@github.com
escreveu:
